# 服务端口
server:
  port: 8160
# 服务名
spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

#mybatis日志
mybatis-plus:
  mapper-locations: classpath:com/tzl/user/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# 微信开放平台 appid
wx:
  open:
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url
    redirect_url: http://localhost:8160/user/wxLogin/callback


