server:
  port: 8005
spring:
  application:
    name: service-msm
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI4Fz7nLmqqW1yrHUngfae
    secret: 81ZPJTux48voQswGj93yWbyBbJH2tq
