server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyId: LTAI4Fz7nLmqqW1yrHUngfae
      keySecret: 81ZPJTux48voQswGj93yWbyBbJH2tq
      bucketName: guli-tzl
